# Generated by Django 3.0.5 on 2020-06-10 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Doctor',
        ),
    ]
