# Generated by Django 3.0.5 on 2020-06-11 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_auto_20200610_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(blank=True, choices=[('d', 'Depressed'), ('a', 'Angry'), ('w', 'Workload'), ('s', 'Sad'), ('r', 'Relationship Problems'), ('t', 'Tensed About Past')], max_length=1)),
                ('mood_date', models.DateField(blank=True, null=True)),
                ('mood_time', models.TimeField(blank=True, null=True)),
                ('yachak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
